### ISSUE TITLE
README should be updated

### ISSUE THREAD

**Issue by valonsejdini** [palantir/encrypted-config-value#102]
The Dropwizard instructions in the README should be updated to note that the 
 system property palantir.config.key_path must be set before running the DW app as otherwise you will end up with following error.  Something like: java -Dpalantir.config.key_path=/path_of_key_file -jar your_dw_app.jar server config.yml , or some other means.

`Caused by: java.nio.file.NoSuchFileException: var/conf/encrypted-config-value.key
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at com.palantir.config.crypto.KeyFileUtils.keyWithTypeFromPath(KeyFileUtils.java:41)
	at com.palantir.config.crypto.KeyFileUtils.keyPairFromPath(KeyFileUtils.java:65)
	at com.palantir.config.crypto.KeyFileUtils.keyPairFromDefaultPath(KeyFileUtils.java:77)
	at com.palantir.config.crypto.KeyFileUtils.decryptUsingDefaultKeys(KeyFileUtils.java:33)
	... 21 more
`

**Comment by Hau-Hau** [comment]
One more reason to update readme is fact that since v6.0.0 dropwizard commands has been decomissed.
