### ISSUE TITLE
"algid parse error, not a sequence" on encrypt-config-value with RSA private key

### ISSUE THREAD

**Issue by cjr8020** [palantir/encrypted-config-value#13]
I wanted to encrypt a config value using the RSA algorithm.
I also wanted to "publish" the public key, and keep the private key private.

Generating RSA key:

```
# java -jar hello-dw.jar generate-random-key -a RSA
Wrote key to var/conf/encrypted-config-value.key
Wrote private key to var/conf/encrypted-config-value.key.private
```

Following your directions: "for encrypting values. In the case of non-symmetric algorithms (e.g. RSA) specify the private key"..

Encrypting a value using private key:

```
$ java -jar hello-dw.jar encrypt-config-value -v mysecret -k var/conf/encrypted-config-value.key.private 
Exception in thread "main" java.lang.RuntimeException: the key was invalid
        at com.palantir.config.crypto.algorithm.EncryptedValueSupplier.silently(EncryptedValueSupplier.java:47)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.getEncryptedValue(RsaAlgorithm.java:54)
        at com.palantir.config.crypto.EncryptConfigValueCommand.run(EncryptConfigValueCommand.java:60)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:80)
        at com.standard.eb.service.MemberUpdateService.main(MemberUpdateService.java:27)
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException: algid parse error, not a sequence
        at sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:205)
        at java.security.KeyFactory.generatePublic(KeyFactory.java:334)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.generatePublicKey(RsaAlgorithm.java:109)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.lambda$getEncryptedValue$2(RsaAlgorithm.java:56)
        at com.palantir.config.crypto.algorithm.EncryptedValueSupplier.silently(EncryptedValueSupplier.java:45)
        ... 5 more
Caused by: java.security.InvalidKeyException: IOException: algid parse error, not a sequence
        at sun.security.x509.X509Key.decode(X509Key.java:398)
        at sun.security.x509.X509Key.decode(X509Key.java:403)
        at sun.security.rsa.RSAPublicKeyImpl.<init>(RSAPublicKeyImpl.java:84)
        at sun.security.rsa.RSAKeyFactory.generatePublic(RSAKeyFactory.java:298)
        at sun.security.rsa.RSAKeyFactory.engineGeneratePublic(RSAKeyFactory.java:201)
        ... 9 more
```

For the sake of experimentation, encrypting a value without referencing the private key explicitly succeeds:

```
$ java -jar hello-dw.jar encrypt-config-value -v mysecret
enc:ZisY+Jd3wXy6OeLa94gjxmo/D2rAgPmIbgk0NPT8o02QH9ShJMr+R0T3+46ZadhgKCxS8eQbo/oP3zzFnmEprIDr7OgPACbCO4Vt0yZjR4LRWJYSxh6ANgatPyTH3BjC+XyJS4yNv455paMgxGddGy6eVSbQ+drc3gbZk4PIL7qxKX9KHMxkrCE0ekgMS3EjKDWPEtxsYaUFf4kwklPqd9zt5vWOUZp9c+NZLmB9epmFxEEH7GguaPsMI6ZpvIDMMC1g/27ofIz3tDHSiJ6FBSmTuzGvvs8AYxVfj/Zb2Zggk09a6e4j+pNPhTsPRXJ/AR+ytw5KfCIeeHXG+bHKhg==
```

... and the service can successfully decrypt the encrypted value in the config.yml.

However, this bundle seems to require that both, public and private, keys are found in `var/conf` directory.

The benefit of using an asymmetric algorithm like RSA would be allowing me to publish the public key and keep the private key private.   I tried moving the private key from `var/conf` directory and leaving just the public key there and got this error:

```
Exception in thread "main" java.lang.RuntimeException: the key was invalid
        at com.palantir.config.crypto.algorithm.DecryptedStringSupplier.silently(DecryptedStringSupplier.java:44)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.getDecryptedString(RsaAlgorithm.java:71)
        at com.palantir.config.crypto.EncryptedValue.getDecryptedValue(EncryptedValue.java:40)
        at com.palantir.config.crypto.EncryptedValue.getDecryptedValue(EncryptedValue.java:53)
        at com.palantir.config.crypto.DecryptingVariableSubstitutor$DecryptingStringLookup.lookup(DecryptingVariableSubstitutor.java:31)
        at org.apache.commons.lang3.text.StrSubstitutor.resolveVariable(StrSubstitutor.java:922)
        at org.apache.commons.lang3.text.StrSubstitutor.substitute(StrSubstitutor.java:843)
        at org.apache.commons.lang3.text.StrSubstitutor.substitute(StrSubstitutor.java:735)
        at org.apache.commons.lang3.text.StrSubstitutor.replace(StrSubstitutor.java:395)
        at io.dropwizard.configuration.SubstitutingSourceProvider.open(SubstitutingSourceProvider.java:38)
        at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:86)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:115)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:64)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:80)
        at com.standard.eb.service.MemberUpdateService.main(MemberUpdateService.java:27)
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : DER input, Integer tag error
        at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:217)
        at java.security.KeyFactory.generatePrivate(KeyFactory.java:372)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.generatePrivateKey(RsaAlgorithm.java:116)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.lambda$getDecryptedString$3(RsaAlgorithm.java:73)
        at com.palantir.config.crypto.algorithm.DecryptedStringSupplier.silently(DecryptedStringSupplier.java:42)
        ... 15 more
Caused by: java.security.InvalidKeyException: IOException : DER input, Integer tag error
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:351)
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:356)
        at sun.security.rsa.RSAPrivateCrtKeyImpl.<init>(RSAPrivateCrtKeyImpl.java:91)
        at sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(RSAPrivateCrtKeyImpl.java:75)
        at sun.security.rsa.RSAKeyFactory.generatePrivate(RSAKeyFactory.java:316)
        at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:213)
        ... 19 more
```

Am I missing something obvious here?
Thanks

**Comment by bavardage** [comment]
To the first point - I made a mistake in the readme, sorry - will push a fix. The public key is used for encryption (producing the encrypted values), the private key for decryption (reading the encrypted values from the config and decrypting them for the app to use).

The readme should say "for encrypting values. In the case of non-symmetric algorithms (e.g. RSA) specify the **public** key"

For the second point, when running, the current code path assumes you have the public and private keys in var/conf, although only the private key is used.

An example use of the non-symmetric keys:
1. Install your service on _host1_, generate the keypair (public and private)
2. Transfer the **public key** to _host2_
3. Install something giving you the encrypted-config-value cli on _host2_
4. Use the cli to encrypt a config value, specifying the path to the **public key**
5. Put that encrypted value into the config on _host1_ (manually/using some deploy script...)
6. Run the service on _host1_, and it will decrypt the value (using the **private key**)

The rough intent here is that only the running service on host1 can read the encrypted values, yet we could produce the configuration files in some other place, as long as we have the public key.

Above you mention "I tried moving the private key from var/conf directory and leaving just the public key there and got this error:". Was this when running your actual dropwizard service or when running a command? From the stacktrace, it looks like the former - in which case, you'll need to have a private key in order to be able to decrypt the value in the config file.

I think a potential enhancement here is to allow running the service without a public key present, since it's kinda superfluous.

**Comment by cjr8020** [comment]
Hi Ben, thanks for looking into this, and great bundle!

The last exception occurred when I was launching the actual dw service with `java -jar server config.yml` as it was attempting to read the config.

It would be a great enhancement if only one key had to be available to the dw service at startup time.   Otherwise, with both, public and private, keys present in one place, there is no real advantage to use RSA over AES.   

Using Alice and Bob as a reference, Alice gives Bob her public key only, and Bob can now create an encrypted message with it.  Alice will use her private key to read the encrypted message.
1. An admin creates an encrypted value by running "encrypt-config-value" (which should ideally only require the **public** key) on host0 (his admin workstation).
2. The dw service instance deployed on hostN should only require the **private** key to be present (in var/conf) in order to be able to decrypt the encrypted config value.

Semantically, you could also reverse the notions, but that's in the eye of the beholder..

Currently this is what happens at dw service startup time when one or the other key is removed from var/conf:

**private** only - the code simply expects to find both:

```
# Exception in thread "main" java.lang.RuntimeException: Was unable to read key
        at com.palantir.config.crypto.EncryptedValue.getDecryptedValue(EncryptedValue.java:55)
        at com.palantir.config.crypto.DecryptingVariableSubstitutor$DecryptingStringLookup.lookup(DecryptingVariableSubstitutor.java:31)
        at org.apache.commons.lang3.text.StrSubstitutor.resolveVariable(StrSubstitutor.java:922)
        at org.apache.commons.lang3.text.StrSubstitutor.substitute(StrSubstitutor.java:843)
        at org.apache.commons.lang3.text.StrSubstitutor.substitute(StrSubstitutor.java:735)
        at org.apache.commons.lang3.text.StrSubstitutor.replace(StrSubstitutor.java:395)
        at io.dropwizard.configuration.SubstitutingSourceProvider.open(SubstitutingSourceProvider.java:38)
        at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:86)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:115)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:64)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:80)
        at com.standard.eb.service.MemberUpdateService.main(MemberUpdateService.java:27)
Caused by: java.nio.file.NoSuchFileException: var/conf/encrypted-config-value.key
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at com.palantir.config.crypto.KeyWithAlgorithm.fromPath(KeyWithAlgorithm.java:66)
        at com.palantir.config.crypto.KeyPair.fromPath(KeyPair.java:66)
        at com.palantir.config.crypto.KeyPair.fromDefaultPath(KeyPair.java:78)
        at com.palantir.config.crypto.EncryptedValue.getDecryptedValue(EncryptedValue.java:50)
        ... 12 more
```

**public** key only in var/conf - the public key cannot be used to decrypt the encrypted value:

```
# Exception in thread "main" java.lang.RuntimeException: the key was invalid
        at com.palantir.config.crypto.algorithm.DecryptedStringSupplier.silently(DecryptedStringSupplier.java:44)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.getDecryptedString(RsaAlgorithm.java:71)
        at com.palantir.config.crypto.EncryptedValue.getDecryptedValue(EncryptedValue.java:40)
        at com.palantir.config.crypto.EncryptedValue.getDecryptedValue(EncryptedValue.java:53)
        at com.palantir.config.crypto.DecryptingVariableSubstitutor$DecryptingStringLookup.lookup(DecryptingVariableSubstitutor.java:31)
        at org.apache.commons.lang3.text.StrSubstitutor.resolveVariable(StrSubstitutor.java:922)
        at org.apache.commons.lang3.text.StrSubstitutor.substitute(StrSubstitutor.java:843)
        at org.apache.commons.lang3.text.StrSubstitutor.substitute(StrSubstitutor.java:735)
        at org.apache.commons.lang3.text.StrSubstitutor.replace(StrSubstitutor.java:395)
        at io.dropwizard.configuration.SubstitutingSourceProvider.open(SubstitutingSourceProvider.java:38)
        at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:86)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:115)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:64)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:80)
        at com.standard.eb.service.MemberUpdateService.main(MemberUpdateService.java:27)
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : DER input, Integer tag error
        at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:217)
        at java.security.KeyFactory.generatePrivate(KeyFactory.java:372)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.generatePrivateKey(RsaAlgorithm.java:116)
        at com.palantir.config.crypto.algorithm.RsaAlgorithm.lambda$getDecryptedString$3(RsaAlgorithm.java:73)
        at com.palantir.config.crypto.algorithm.DecryptedStringSupplier.silently(DecryptedStringSupplier.java:42)
        ... 15 more
Caused by: java.security.InvalidKeyException: IOException : DER input, Integer tag error
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:351)
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:356)
        at sun.security.rsa.RSAPrivateCrtKeyImpl.<init>(RSAPrivateCrtKeyImpl.java:91)
        at sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(RSAPrivateCrtKeyImpl.java:75)
        at sun.security.rsa.RSAKeyFactory.generatePrivate(RSAKeyFactory.java:316)
        at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:213)
        ... 19 more
```

**Comment by markelliot** [comment]
Where the RSA keys become useful is if you store your config files (but not the secrets) somewhere more public (eg a git repo)...if you're not doing that, you're right, there's not much benefit of one implementation over the other. 

In the end, if your service needs to load a value, it's going to need the private key, and the public key can be known to everyone, so it's presence doesn't have meaningful impact on the security concern. 

From what you've described so far, I'd wager the two implementations end up being functionally equivalent in your setup.

**Comment by cjr8020** [comment]
Mark - you're right. 
Thanks for the discussion.
