### ISSUE TITLE
1.0.2 compatibility with dw 1.0.x

### ISSUE THREAD

**Issue by cjr8020** [palantir/encrypted-config-value#54]
it doesn't look like 1.0.2 is compatible with dw v1.0.5.   This combination yields the exception below.
Changing back to dw v0.9.2 - no problem.  
Are you targeting compatibility with dw v1.0.x in the next release? 
Thanks!

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: class com.palantir.config.crypto.SubstitutingConfigurationFactory has interface io.dropwizard.configuration.ConfigurationFactory as super class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.palantir.config.crypto.SubstitutingConfigurationFactory$Factory.create(SubstitutingConfigurationFactory.java:104)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:122)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:72)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at com.standard.service.SomeService.main(SomeService.java:21)
```

**Comment by markelliot** [comment]
There's a separate published artifact for Dropwizard 1.x, is this with that artifact or the same one that you're using for DW 0.9.2? (the latter definitely won't work)

**Comment by cjr8020** [comment]
Oh, I see 

```
<artifactId>encrypted-config-value-bundle-dropwizard1</artifactId>
```
The exception was with the same one: `encrypted-config-value-bundle`

Thanks for clarifying
